"""
Instructions - In this game, the user gets the first chance to pick the option between Rock, paper, and scissors.
After that computer select from the choices(randomly), the winner is decided as per the rules.
If the game is tied, then players keep playing until one player wins.
Rock vs Paper -> Paper wins!
Rock vs Scissor -> Scissor wins!
Paper vs Scissor -> Scissor wins!
"""

import random

# Print the rules of game
print('Rules of the game ROCK PAPER SCISSORS are :\n'
          + "Rock vs Paper -> Paper wins \n"
          + "Rock vs Scissors -> Rock wins \n"
          + "Paper vs Scissors -> Scissor wins \n")
while True:
    # fetch user's choice from Rock, Paper, Scissors
    userChoice = int(input("1 - Rock \n2 - Paper \n3 - Scissors \nEnter your choice:"))

    # Check if user has entered valid number (1-3)
    if userChoice > 3 or userChoice < 1:
        print("Enter a valid choice!!")

    # function to map name from the numeric choices (ex - 1 will mean Rock)
    def setChoiceName(choice):
        if choice == 1:
            choice_name = 'Rock'
        elif choice == 2:
            choice_name = 'Paper'
        else:
            choice_name = 'Scissors'
        return choice_name


    user_choice_name = setChoiceName(userChoice)
    print("Your choice is", user_choice_name)
    print('Now its Computers Turn....')

    # generate a random number between the range of 1 and 3
    compChoice = random.randint(1, 3)

    # call setChoiceName to map name to numeric value generated by computer
    comp_choice_name = setChoiceName(compChoice)
    print("Computer's choice is", comp_choice_name,
          "\nYou vs Computer. Who will win?\n" + user_choice_name, "v/s", comp_choice_name)

    # case: user choice = computer's choice => draw
    if userChoice == compChoice:
        print("<== Its a tie ==>")
        result = "DRAW"
    # case: rock(by user) vs paper(by computer) or paper(by user) vs rock(by computer) => paper wins
    elif userChoice == 1 and compChoice == 2 or userChoice == 2 and compChoice == 1:
        print('paper wins =>', end="")
        result = 'Paper'
    # case: rock(by user) vs scissors(by computer) or scissors(by user) vs rock(by computer) => rock wins
    elif userChoice == 1 and compChoice == 3 or userChoice == 3 and compChoice == 1:
        print('Rock wins =>\n', end="")
        result = 'Rock'
    # case: paper(by user) vs scissors(by computer) or scissors(by user) vs paper(by computer) => scissors wins
    elif userChoice == 2 and compChoice == 3 or userChoice == 3 and compChoice == 2:
        print('Scissors wins =>', end="")
        result = 'Scissors'

    # if game is not tied then check if user won or computer won
    if not result == "DRAW":
        if result == user_choice_name:
            print("<== User wins ==>")
        else:
            print("<== Computer wins ==>")
        response = input("Do you want to restart ? Y or N:")
        if not (response == "Y" or response == "y"):
            break

print("---------GAME OVER----------")
